name: GriefPreventionNG
version: "${git.commit.id.describe}"
api-version: "1.20"
main: me.tinyoverflow.griefprevention.GriefPrevention
loader: me.tinyoverflow.griefprevention.GriefPreventionLoader

dependencies:
  - name: Vault
    required: false
  - name: WorldGuard
    required: false
  - name: WorldEdit
    required: false